### ISSUE TITLE
关于自定义回复在log on时的问题

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice#7]
以下为原需求提出者的描述：

由于海豹骰支持多种回复匹配方式，误触的概率较仅精准匹配下提升了很多，带团时一旦误触可能会带来不利于跑团的影响，然而平时互动（如今晚吃什么/今日运势等）又需要强大的自定义回复功能。希望可以在跑团（即log on之后）时实现自动关闭自定义回复的功能，在跑团结束（log off/log end）时恢复当前群自定义回复的设置。

**Comment by Szzrain** [comment]
我本人的想法：

因为有些人可能需要在log on时保持自定义回复打开，因此，我觉得加入一个变量名为$tlogon是不是要更好一些，这样就能在自定义回复内判断日志记录的开关状态，能够同时满足两边的想法

**Comment by fy0** [comment]
新的临时变量 $t游戏模式 t当前记录
