### ISSUE TITLE
[BUG] coc自定义文案中的属性设置_保存提醒触发条件需要修改

### ISSUE THREAD

**Issue by asterson** [sealdice/sealdice#80]
**描述你遇到的 bug**
coc自定义文案中用于st hp+1等指令的【属性设置_保存提醒】默认情况下，只有是绑定卡时才能触发。
然而绑定卡是自动保存角色数据的，并不需要保存提醒。需要改为不是绑定卡时修改角色属性才会触发保存提醒。

**如何复现**
复现此bug的步骤:
例子:
1. 重置属性设置_保存提醒
2. 在绑定卡状态下发送。st hp+1
3. 触发保存提醒

**你期望发生的**
不是绑定卡时修改角色属性才触发保存提醒。

**实际上发生的**
是绑定卡时触发了保存提醒，不是绑定卡反而不能触发

**日志/屏幕截图**
![Screenshot_20230213_015304_com android chrome](https://user-images.githubusercontent.com/30658881/218350898-51d19133-dd34-40c6-aba2-61f6510ee1af.png)

**环境信息:**
 - 海豹版本: 1.1.2fix v20230109
 - 运行环境: Windows
 - 帐号类型: QQ, kook
 - 使用协议: Android

**Comment by fy0** [comment]
属性设置_保存提醒 写反了：
改为
{ $t当前绑定角色 ? '' : '角色信息已经变更，别忘了使用.pc save来进行保存！' }
